-- Migration 131: Ruim dubbele FK-constraints op (inkoop-module)
--
-- Root cause: de tabellen `inkooporders`, `inkooporder_regels`, `rollen`
-- bestonden al als stub met autogenerated FK-namen `<tabel>_<kolom>_fkey`.
-- Migratie 127 voegde tweede FK's toe onder mijn eigen naamconventie
-- (`inkooporders_leverancier_fk` etc.). PostgREST kan niet kiezen tussen
-- twee gelijke FK's bij een embed — error PGRST201.
--
-- Fix: drop mijn toegevoegde `_fk`-constraints. De oude `_fkey` varianten
-- doen exact hetzelfde werk en zijn de PostgREST-conventie.
--
-- Defensief: als de oude `_fkey` toevallig NIET bestond, voegen we die
-- alsnog toe onder de conventionele naam.
--
-- Idempotent.

-- ============================================================================
-- inkooporders.leverancier_id → leveranciers.id
-- ============================================================================
ALTER TABLE inkooporders DROP CONSTRAINT IF EXISTS inkooporders_leverancier_fk;

DO $$ BEGIN
  ALTER TABLE inkooporders
    ADD CONSTRAINT inkooporders_leverancier_id_fkey
    FOREIGN KEY (leverancier_id) REFERENCES leveranciers(id) ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ============================================================================
-- inkooporder_regels.inkooporder_id → inkooporders.id
-- ============================================================================
ALTER TABLE inkooporder_regels DROP CONSTRAINT IF EXISTS inkooporder_regels_order_fk;

DO $$ BEGIN
  ALTER TABLE inkooporder_regels
    ADD CONSTRAINT inkooporder_regels_inkooporder_id_fkey
    FOREIGN KEY (inkooporder_id) REFERENCES inkooporders(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ============================================================================
-- inkooporder_regels.artikelnr → producten.artikelnr
-- ============================================================================
ALTER TABLE inkooporder_regels DROP CONSTRAINT IF EXISTS inkooporder_regels_artikelnr_fk;

DO $$ BEGIN
  ALTER TABLE inkooporder_regels
    ADD CONSTRAINT inkooporder_regels_artikelnr_fkey
    FOREIGN KEY (artikelnr) REFERENCES producten(artikelnr) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ============================================================================
-- rollen.inkooporder_regel_id → inkooporder_regels.id
-- ============================================================================
ALTER TABLE rollen DROP CONSTRAINT IF EXISTS rollen_inkooporder_regel_fk;

DO $$ BEGIN
  ALTER TABLE rollen
    ADD CONSTRAINT rollen_inkooporder_regel_id_fkey
    FOREIGN KEY (inkooporder_regel_id) REFERENCES inkooporder_regels(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ============================================================================
-- Forceer PostgREST schema-cache reload (Supabase luistert op deze NOTIFY)
-- ============================================================================
NOTIFY pgrst, 'reload schema';
